# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  flutter_jobs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Flutter environment
      uses: subosito/flutter-action@v2
      with:
        flutter-channel: 'master' 

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Format Flutter code
      run: dart format --set-exit-if-changed .

    - name: Analyze Flutter code
      run: dart analyze
